### ISSUE TITLE
眼在手外的精度验证

### ISSUE THREAD

**Issue by sheiling** [ZiqiChai/simplified_eye_hand_calibration#1]
你好，当我使用 eye_to_hand_calibration 做眼在手外的精度验证时，得到变换矩阵后，反算相机位姿时，发现精度比较低

**Comment by ZiqiChai** [comment]
当使用UR机器人以外的其他机器人时，我也会遇到问题，我会找时间尽快排查和完善。

**Comment by ZiqiChai** [comment]
> 你好，当我使用 eye_to_hand_calibration 做眼在手外的精度验证时，得到变换矩阵后，反算相机位姿时，发现精度比较低

当使用UR机器人以外的其他机器人时，我也会遇到问题，我会找时间尽快排查和完善。

**Comment by lumenma** [comment]
您好，您的示例数据链接我怎麼也打不开，您能给我发一份吗，我的邮箱luchg68@163.com,万分感谢。

**Comment by sheiling** [comment]
你好，数据已经被删除了




------------------&nbsp;Original message&nbsp;------------------
From: "陆门马"; 
Sendtime: Wednesday, Aug 25, 2021 6:49 PM
To: "ZiqiChai/simplified_eye_hand_calibration"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [ZiqiChai/simplified_eye_hand_calibration] 眼在手外的精度验证 (#1)





 
***@***.***,万分感谢。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZiqiChai** [comment]
由于交大云盘JBox不再接受对外访问，因此示例数据已经从交大云盘转到CSDN网站，无需积分即可下载。见README。

**Comment by ZiqiChai** [comment]
由于交大云盘JBox不再接受对外访问，因此示例数据已经从交大云盘转到CSDN网站，无需积分即可下载。见README。

**Comment by YMH-H** [comment]
你好，我使用的也是UR5e机械臂，在做eye_to_hand实验时使用了自己拍的数据，得到变换矩阵之后计算AX=XB的误差时，平移误差较大，大概有1-2cm，变换矩阵也无法应用到实际抓取实验，请问这是什么原因啊0.0
