### ISSUE TITLE
could you provide example calibration data

### ISSUE THREAD

**Issue by wawatt** [ZiqiChai/simplified_eye_hand_calibration#2]
could you provide example calibration data

**Comment by ZiqiChai** [comment]
Yes, as described in [README.md](https://github.com/ZiqiChai/simplified_eye_hand_calibration/blob/master/README.md), you can download an example at [https://jbox.sjtu.edu.cn/l/KnHCaC](https://jbox.sjtu.edu.cn/l/KnHCaC).

![image](https://user-images.githubusercontent.com/26563401/115799105-57869c80-a40a-11eb-8010-301043f844ae.png)

**Comment by ZiqiChai** [comment]
A new link to download an example data can be found at  [README.md](https://github.com/ZiqiChai/simplified_eye_hand_calibration/blob/master/README.md).
